/* =========================================================
   HI-TECH — Catalogue produits
   ---------------------------------------------------------
   Pour modifier le catalogue, éditez simplement ce fichier :
   - price   : prix en FCFA (nombre, sans espaces). 0 = "Prix sur demande"
   - oldPrice: ancien prix barré (optionnel)
   - img     : photo du produit (img/p/...) ; sinon une icône est affichée
   - colors  : [{ name, hex, img }] — chaque pastille de couleur affiche sa photo officielle
   - badge   : "Neuf", "Reconditionné", "Promo", "Nouveau"...
   - options : variantes proposées (capacité, couleur...)
   - series  : gamme affichée en sous-filtre dans la boutique (Galaxy S, Galaxy A…)
   Les prix ci-dessous sont INDICATIFS : à mettre à jour par la boutique.
   ========================================================= */

const WHATSAPP_NUMBER = "221775318192"; // 77 531 81 92
const PHONE_1 = "+221 77 531 81 92";
const PHONE_2 = "+221 76 531 81 92";

const CATEGORIES = [
  { id: "iphone",      label: "iPhone",       icon: "phone"   },
  { id: "android",     label: "Android",      icon: "android" },
  { id: "ordinateur",  label: "Ordinateurs",  icon: "laptop"  },
  { id: "tablette",    label: "Tablettes",    icon: "tablet"  },
  { id: "montre",      label: "Montres",      icon: "watch"   },
  { id: "audio",       label: "Audio",        icon: "audio"   },
  { id: "gaming",      label: "PlayStation",  icon: "gamepad" },
  { id: "accessoires", label: "Accessoires",  icon: "plug"    }
];

const PRODUCTS = [
  { id: "ip18pm", cat: "iphone", series: "iPhone 18", brand: "Apple", name: "iPhone 18 Pro Max", price: 1250000, badge: "Nouveau", colors: [{"name": "Bordeaux", "hex": "#4d1821", "img": "img/p/apple/ip18pm-bordeaux.jpg"}, {"name": "Argent", "hex": "#f7f7f7", "img": "img/p/apple/ip18pm-argent.jpg"}, {"name": "Glacier", "hex": "#e8f2ff", "img": "img/p/apple/ip18pm-glacier.jpg"}, {"name": "Noir", "hex": "#3c3c3c", "img": "img/p/apple/ip18pm-noir.jpg"}], options: ["256 Go", "512 Go", "1 To"], desc: "Le plus grand écran et la meilleure autonomie jamais vus sur un iPhone.", featured: true },
  { id: "ip18p", cat: "iphone", series: "iPhone 18", brand: "Apple", name: "iPhone 18 Pro", price: 1100000, badge: "Nouveau", colors: [{"name": "Argent", "hex": "#f7f7f7", "img": "img/p/apple/ip18p-argent.jpg"}, {"name": "Bordeaux", "hex": "#4d1821", "img": "img/p/apple/ip18p-bordeaux.jpg"}, {"name": "Glacier", "hex": "#e8f2ff", "img": "img/p/apple/ip18p-glacier.jpg"}, {"name": "Noir", "hex": "#3c3c3c", "img": "img/p/apple/ip18p-noir.jpg"}], options: ["256 Go", "512 Go", "1 To"], desc: "Puissance pro, triple caméra 48 Mpx, design en aluminium." },
  { id: "ipduo", cat: "iphone", series: "iPhone Duo / Air", brand: "Apple", name: "iPhone Duo", price: 1650000, badge: "Nouveau", colors: [{"name": "Ciel nocturne", "hex": "#394452", "img": "img/p/apple/ipduo-ciel-nocturne.jpg"}, {"name": "Blanc étoile", "hex": "#f7f6f5", "img": "img/p/apple/ipduo-blanc-etoile.jpg"}], options: ["512 Go", "1 To"], desc: "Le premier iPhone pliable : un grand écran qui se glisse dans la poche.", featured: true },
  { id: "ipair", cat: "iphone", series: "iPhone Duo / Air", brand: "Apple", name: "iPhone Air", price: 850000, badge: "Neuf", colors: [{"name": "Bleu ciel", "hex": "#e5f2fa", "img": "img/p/apple/ipair-bleu-ciel.jpg"}, {"name": "Or clair", "hex": "#faf3e5", "img": "img/p/apple/ipair-or-clair.jpg"}, {"name": "Blanc nuage", "hex": "#fcfcfc", "img": "img/p/apple/ipair-blanc-nuage.jpg"}, {"name": "Noir sidéral", "hex": "#131313", "img": "img/p/apple/ipair-noir-sideral.jpg"}], options: ["256 Go", "512 Go", "1 To"], desc: "L'iPhone le plus fin jamais conçu." },
  { id: "ip17pm", cat: "iphone", series: "iPhone 17", brand: "Apple", name: "iPhone 17 Pro Max", price: 950000, oldPrice: 1050000, badge: "Promo", colors: [{"name": "Orange cosmique", "hex": "#e2783c", "img": "img/p/apple/ip17pm-orange-cosmique.jpg"}, {"name": "Bleu intense", "hex": "#33415f", "img": "img/p/apple/ip17pm-bleu-intense.jpg"}, {"name": "Argent", "hex": "#dcdcdc", "img": "img/p/apple/ip17pm-argent.jpg"}], options: ["256 Go", "512 Go", "1 To"], desc: "Puce A19 Pro, triple caméra 48 Mpx, autonomie record." },
  { id: "ip17p", cat: "iphone", series: "iPhone 17", brand: "Apple", name: "iPhone 17 Pro", price: 850000, badge: "Neuf", colors: [{"name": "Argent", "hex": "#dcdcdc", "img": "img/p/apple/ip17p-argent.jpg"}, {"name": "Orange cosmique", "hex": "#e2783c", "img": "img/p/apple/ip17p-orange-cosmique.jpg"}, {"name": "Bleu intense", "hex": "#33415f", "img": "img/p/apple/ip17p-bleu-intense.jpg"}], options: ["256 Go", "512 Go"], desc: "Écran ProMotion 120 Hz, téléobjectif 48 Mpx." },
  { id: "ip17", cat: "iphone", series: "iPhone 17", brand: "Apple", name: "iPhone 17", price: 620000, badge: "Neuf", colors: [{"name": "Bleu brume", "hex": "#a9bdde", "img": "img/p/apple/ip17-bleu-brume.jpg"}, {"name": "Lavande", "hex": "#e8d8f2", "img": "img/p/apple/ip17-lavande.jpg"}, {"name": "Sauge", "hex": "#b9c69c", "img": "img/p/apple/ip17-sauge.jpg"}, {"name": "Blanc", "hex": "#fcfcfc", "img": "img/p/apple/ip17-blanc.jpg"}, {"name": "Noir", "hex": "#444647", "img": "img/p/apple/ip17-noir.jpg"}], options: ["256 Go", "512 Go"], desc: "Écran ProMotion, caméra 48 Mpx, puce A19." },
  { id: "ip17e", cat: "iphone", series: "iPhone 17", brand: "Apple", name: "iPhone 17e", price: 430000, badge: "Neuf", colors: [{"name": "Rose pâle", "hex": "#fce7e6", "img": "img/p/apple/ip17e-rose-pale.jpg"}, {"name": "Blanc", "hex": "#fafafa", "img": "img/p/apple/ip17e-blanc.jpg"}, {"name": "Noir", "hex": "#4a4e50", "img": "img/p/apple/ip17e-noir.jpg"}], options: ["128 Go", "256 Go"], desc: "L'essentiel de l'iPhone à petit prix." },
  { id: "ip16pm", cat: "iphone", series: "iPhone 16", brand: "Apple", name: "iPhone 16 Pro Max", price: 720000, badge: "Neuf", colors: [{"name": "Titane désert", "hex": "#bfa48f", "img": "img/p/apple/ip16pm-titane-desert.jpg"}, {"name": "Titane naturel", "hex": "#bab4a9", "img": "img/p/apple/ip16pm-titane-naturel.jpg"}, {"name": "Titane blanc", "hex": "#f2f1ed", "img": "img/p/apple/ip16pm-titane-blanc.jpg"}, {"name": "Titane noir", "hex": "#3c3c3d", "img": "img/p/apple/ip16pm-titane-noir.jpg"}], options: ["256 Go", "512 Go"], desc: "Écran 6,9 pouces, titane, puce A18 Pro." },
  { id: "ip16p", cat: "iphone", series: "iPhone 16", brand: "Apple", name: "iPhone 16 Pro", price: 650000, badge: "Neuf", colors: [{"name": "Titane désert", "hex": "#bfa48f", "img": "img/p/apple/ip16p-titane-desert.jpg"}, {"name": "Titane naturel", "hex": "#bab4a9", "img": "img/p/apple/ip16p-titane-naturel.jpg"}, {"name": "Titane blanc", "hex": "#f2f1ed", "img": "img/p/apple/ip16p-titane-blanc.jpg"}, {"name": "Titane noir", "hex": "#3c3c3d", "img": "img/p/apple/ip16p-titane-noir.jpg"}], options: ["128 Go", "256 Go", "512 Go"], desc: "Titane, triple caméra 48 Mpx, puce A18 Pro." },
  { id: "ip16plus", cat: "iphone", series: "iPhone 16", brand: "Apple", name: "iPhone 16 Plus", price: 540000, badge: "Neuf", colors: [{"name": "Outremer", "hex": "#9aadf6", "img": "img/p/apple/ip16plus-outremer.jpg"}, {"name": "Sarcelle", "hex": "#b0d4d2", "img": "img/p/apple/ip16plus-sarcelle.jpg"}, {"name": "Rose", "hex": "#f9d9d5", "img": "img/p/apple/ip16plus-rose.jpg"}, {"name": "Blanc", "hex": "#f5f5f0", "img": "img/p/apple/ip16plus-blanc.jpg"}, {"name": "Noir", "hex": "#2b2b2d", "img": "img/p/apple/ip16plus-noir.jpg"}], options: ["128 Go", "256 Go"], desc: "Grand écran 6,7 pouces, autonomie record." },
  { id: "ip16", cat: "iphone", series: "iPhone 16", brand: "Apple", name: "iPhone 16", price: 480000, badge: "Neuf", colors: [{"name": "Outremer", "hex": "#a1b2f7", "img": "img/p/apple/ip16-outremer.jpg"}, {"name": "Sarcelle", "hex": "#b5d7d4", "img": "img/p/apple/ip16-sarcelle.jpg"}, {"name": "Rose", "hex": "#f3b2dd", "img": "img/p/apple/ip16-rose.jpg"}, {"name": "Blanc", "hex": "#fafafa", "img": "img/p/apple/ip16-blanc.jpg"}, {"name": "Noir", "hex": "#4a4e50", "img": "img/p/apple/ip16-noir.jpg"}], options: ["128 Go", "256 Go"], desc: "Puce A18, bouton Action, caméra Fusion 48 Mpx." },
  { id: "ip16e", cat: "iphone", series: "iPhone 16", brand: "Apple", name: "iPhone 16e", price: 390000, badge: "Neuf", colors: [{"name": "Blanc", "hex": "#f5f5f0", "img": "img/p/apple/ip16e-blanc.jpg"}, {"name": "Noir", "hex": "#2b2b2d", "img": "img/p/apple/ip16e-noir.jpg"}], options: ["128 Go", "256 Go"], desc: "Puce A18 et caméra 48 Mpx à petit prix." },
  { id: "ip15pm", cat: "iphone", series: "iPhone 15", brand: "Apple", name: "iPhone 15 Pro Max", price: 580000, badge: "Reconditionné", colors: [{"name": "Titane naturel", "hex": "#bab4a9", "img": "img/p/apple/ip15pm-titane-naturel.jpg"}, {"name": "Titane bleu", "hex": "#3f4a58", "img": "img/p/apple/ip15pm-titane-bleu.jpg"}, {"name": "Titane blanc", "hex": "#f2f1ed", "img": "img/p/apple/ip15pm-titane-blanc.jpg"}, {"name": "Titane noir", "hex": "#3c3c3d", "img": "img/p/apple/ip15pm-titane-noir.jpg"}], options: ["256 Go", "512 Go"], desc: "Titane, zoom 5x, USB-C. Testé et garanti." },
  { id: "ip15p", cat: "iphone", series: "iPhone 15", brand: "Apple", name: "iPhone 15 Pro", price: 520000, badge: "Reconditionné", colors: [{"name": "Titane naturel", "hex": "#bab4a9", "img": "img/p/apple/ip15p-titane-naturel.jpg"}, {"name": "Titane bleu", "hex": "#3f4a58", "img": "img/p/apple/ip15p-titane-bleu.jpg"}, {"name": "Titane blanc", "hex": "#f2f1ed", "img": "img/p/apple/ip15p-titane-blanc.jpg"}, {"name": "Titane noir", "hex": "#3c3c3d", "img": "img/p/apple/ip15p-titane-noir.jpg"}], options: ["128 Go", "256 Go"], desc: "Titane, puce A17 Pro, bouton Action. Testé et garanti." },
  { id: "ip15plus", cat: "iphone", series: "iPhone 15", brand: "Apple", name: "iPhone 15 Plus", price: 480000, badge: "Reconditionné", colors: [{"name": "Bleu", "hex": "#d4e4ed", "img": "img/p/apple/ip15plus-bleu.jpg"}, {"name": "Rose", "hex": "#f6dadc", "img": "img/p/apple/ip15plus-rose.jpg"}, {"name": "Jaune", "hex": "#f9e5c2", "img": "img/p/apple/ip15plus-jaune.jpg"}, {"name": "Vert", "hex": "#e3e9d9", "img": "img/p/apple/ip15plus-vert.jpg"}, {"name": "Noir", "hex": "#2b2b2d", "img": "img/p/apple/ip15plus-noir.jpg"}], options: ["128 Go", "256 Go"], desc: "Dynamic Island, grand écran 6,7 pouces, USB-C." },
  { id: "ip15", cat: "iphone", series: "iPhone 15", brand: "Apple", name: "iPhone 15", price: 430000, badge: "Reconditionné", colors: [{"name": "Bleu", "hex": "#d4e4ed", "img": "img/p/apple/ip15-bleu.jpg"}, {"name": "Rose", "hex": "#f6dadc", "img": "img/p/apple/ip15-rose.jpg"}, {"name": "Jaune", "hex": "#f9e5c2", "img": "img/p/apple/ip15-jaune.jpg"}, {"name": "Vert", "hex": "#e3e9d9", "img": "img/p/apple/ip15-vert.jpg"}, {"name": "Noir", "hex": "#2b2b2d", "img": "img/p/apple/ip15-noir.jpg"}], options: ["128 Go", "256 Go"], desc: "Dynamic Island, caméra 48 Mpx, USB-C." },
  { id: "ip14pm", cat: "iphone", series: "iPhone 14", brand: "Apple", name: "iPhone 14 Pro Max", price: 450000, badge: "Reconditionné", colors: [{"name": "Violet intense", "hex": "#594f63", "img": "img/p/apple/ip14pm-violet-intense.jpg"}, {"name": "Or", "hex": "#f5dcc4", "img": "img/p/apple/ip14pm-or.jpg"}, {"name": "Argent", "hex": "#e3e4e5", "img": "img/p/apple/ip14pm-argent.jpg"}, {"name": "Noir sidéral", "hex": "#403e3d", "img": "img/p/apple/ip14pm-noir-sideral.jpg"}], options: ["128 Go", "256 Go"], desc: "Dynamic Island, caméra 48 Mpx, écran toujours activé." },
  { id: "ip14p", cat: "iphone", series: "iPhone 14", brand: "Apple", name: "iPhone 14 Pro", price: 400000, badge: "Reconditionné", colors: [{"name": "Violet intense", "hex": "#594f63", "img": "img/p/apple/ip14p-violet-intense.jpg"}, {"name": "Or", "hex": "#f5dcc4", "img": "img/p/apple/ip14p-or.jpg"}, {"name": "Argent", "hex": "#e3e4e5", "img": "img/p/apple/ip14p-argent.jpg"}, {"name": "Noir sidéral", "hex": "#403e3d", "img": "img/p/apple/ip14p-noir-sideral.jpg"}], options: ["128 Go", "256 Go"], desc: "Dynamic Island, caméra 48 Mpx." },
  { id: "ip14plus", cat: "iphone", series: "iPhone 14", brand: "Apple", name: "iPhone 14 Plus", price: 330000, badge: "Reconditionné", colors: [{"name": "Bleu", "hex": "#a0b4c7", "img": "img/p/apple/ip14plus-bleu.jpg"}, {"name": "Mauve", "hex": "#e5ddea", "img": "img/p/apple/ip14plus-mauve.jpg"}, {"name": "Lumière stellaire", "hex": "#f2ece4", "img": "img/p/apple/ip14plus-lumiere-stellaire.jpg"}, {"name": "Minuit", "hex": "#232a31", "img": "img/p/apple/ip14plus-minuit.jpg"}], options: ["128 Go", "256 Go"], desc: "Grand écran 6,7 pouces, excellente autonomie." },
  { id: "ip14", cat: "iphone", series: "iPhone 14", brand: "Apple", name: "iPhone 14", price: 300000, badge: "Reconditionné", colors: [{"name": "Bleu", "hex": "#a0b4c7", "img": "img/p/apple/ip14-bleu.jpg"}, {"name": "Mauve", "hex": "#e5ddea", "img": "img/p/apple/ip14-mauve.jpg"}, {"name": "Lumière stellaire", "hex": "#f2ece4", "img": "img/p/apple/ip14-lumiere-stellaire.jpg"}, {"name": "Minuit", "hex": "#232a31", "img": "img/p/apple/ip14-minuit.jpg"}], options: ["128 Go", "256 Go"], desc: "Puce A15, double caméra, détection des accidents." },
  { id: "ip13pm", cat: "iphone", series: "iPhone 13", brand: "Apple", name: "iPhone 13 Pro Max", price: 350000, badge: "Reconditionné", colors: [{"name": "Bleu alpin", "hex": "#a7c1d9", "img": "img/p/apple/ip13pm-bleu-alpin.jpg"}, {"name": "Vert alpin", "hex": "#576856", "img": "img/p/apple/ip13pm-vert-alpin.jpg"}, {"name": "Or", "hex": "#f5dcc4", "img": "img/p/apple/ip13pm-or.jpg"}, {"name": "Argent", "hex": "#e3e4e5", "img": "img/p/apple/ip13pm-argent.jpg"}, {"name": "Graphite", "hex": "#52514f", "img": "img/p/apple/ip13pm-graphite.jpg"}], options: ["128 Go", "256 Go"], desc: "Écran ProMotion 120 Hz, triple caméra." },
  { id: "ip13p", cat: "iphone", series: "iPhone 13", brand: "Apple", name: "iPhone 13 Pro", price: 300000, badge: "Reconditionné", colors: [{"name": "Bleu alpin", "hex": "#a7c1d9", "img": "img/p/apple/ip13p-bleu-alpin.jpg"}, {"name": "Vert alpin", "hex": "#576856", "img": "img/p/apple/ip13p-vert-alpin.jpg"}, {"name": "Or", "hex": "#f5dcc4", "img": "img/p/apple/ip13p-or.jpg"}, {"name": "Argent", "hex": "#e3e4e5", "img": "img/p/apple/ip13p-argent.jpg"}, {"name": "Graphite", "hex": "#52514f", "img": "img/p/apple/ip13p-graphite.jpg"}], options: ["128 Go", "256 Go"], desc: "Écran ProMotion 120 Hz, triple caméra." },
  { id: "ip13", cat: "iphone", series: "iPhone 13", brand: "Apple", name: "iPhone 13", price: 240000, badge: "Reconditionné", colors: [{"name": "Bleu", "hex": "#276787", "img": "img/p/apple/ip13-bleu.jpg"}, {"name": "Rose", "hex": "#f9d9d5", "img": "img/p/apple/ip13-rose.jpg"}, {"name": "(PRODUCT)RED", "hex": "#ba0c2e", "img": "img/p/apple/ip13-product-red.jpg"}, {"name": "Lumière stellaire", "hex": "#f2ece4", "img": "img/p/apple/ip13-lumiere-stellaire.jpg"}, {"name": "Minuit", "hex": "#232a31", "img": "img/p/apple/ip13-minuit.jpg"}], options: ["128 Go", "256 Go"], desc: "Puce A15, double caméra, très bonne autonomie." },
  { id: "ip13mini", cat: "iphone", series: "iPhone 13", brand: "Apple", name: "iPhone 13 mini", price: 210000, badge: "Reconditionné", colors: [{"name": "Bleu", "hex": "#276787", "img": "img/p/apple/ip13mini-bleu.jpg"}, {"name": "Rose", "hex": "#f9d9d5", "img": "img/p/apple/ip13mini-rose.jpg"}, {"name": "(PRODUCT)RED", "hex": "#ba0c2e", "img": "img/p/apple/ip13mini-product-red.jpg"}, {"name": "Lumière stellaire", "hex": "#f2ece4", "img": "img/p/apple/ip13mini-lumiere-stellaire.jpg"}, {"name": "Minuit", "hex": "#232a31", "img": "img/p/apple/ip13mini-minuit.jpg"}], options: ["128 Go", "256 Go"], desc: "Tout l'iPhone 13 dans un format compact." },
  { id: "ip12pm", cat: "iphone", series: "iPhone 12", brand: "Apple", name: "iPhone 12 Pro Max", price: 270000, badge: "Reconditionné", colors: [{"name": "Bleu Pacifique", "hex": "#2d4e5c", "img": "img/p/apple/ip12pm-bleu-pacifique.jpg"}, {"name": "Or", "hex": "#f5dcc4", "img": "img/p/apple/ip12pm-or.jpg"}, {"name": "Argent", "hex": "#e3e4e5", "img": "img/p/apple/ip12pm-argent.jpg"}, {"name": "Graphite", "hex": "#52514f", "img": "img/p/apple/ip12pm-graphite.jpg"}], options: ["128 Go", "256 Go"], desc: "Grand écran 6,7 pouces, triple caméra, 5G." },
  { id: "ip12p", cat: "iphone", series: "iPhone 12", brand: "Apple", name: "iPhone 12 Pro", price: 230000, badge: "Reconditionné", colors: [{"name": "Bleu Pacifique", "hex": "#2d4e5c", "img": "img/p/apple/ip12p-bleu-pacifique.jpg"}, {"name": "Or", "hex": "#f5dcc4", "img": "img/p/apple/ip12p-or.jpg"}, {"name": "Argent", "hex": "#e3e4e5", "img": "img/p/apple/ip12p-argent.jpg"}, {"name": "Graphite", "hex": "#52514f", "img": "img/p/apple/ip12p-graphite.jpg"}], options: ["128 Go", "256 Go"], desc: "Triple caméra, LiDAR, 5G." },
  { id: "ip12", cat: "iphone", series: "iPhone 12", brand: "Apple", name: "iPhone 12", price: 180000, badge: "Reconditionné", colors: [{"name": "Bleu", "hex": "#023b63", "img": "img/p/apple/ip12-bleu.jpg"}, {"name": "Vert", "hex": "#d8efd5", "img": "img/p/apple/ip12-vert.jpg"}, {"name": "(PRODUCT)RED", "hex": "#ba0c2e", "img": "img/p/apple/ip12-product-red.jpg"}, {"name": "Blanc", "hex": "#f5f5f0", "img": "img/p/apple/ip12-blanc.jpg"}, {"name": "Noir", "hex": "#2b2b2d", "img": "img/p/apple/ip12-noir.jpg"}], options: ["64 Go", "128 Go", "256 Go"], desc: "Écran OLED, 5G, MagSafe." },
  { id: "ip12mini", cat: "iphone", series: "iPhone 12", brand: "Apple", name: "iPhone 12 mini", price: 150000, badge: "Reconditionné", colors: [{"name": "Bleu", "hex": "#023b63", "img": "img/p/apple/ip12mini-bleu.jpg"}, {"name": "Vert", "hex": "#d8efd5", "img": "img/p/apple/ip12mini-vert.jpg"}, {"name": "(PRODUCT)RED", "hex": "#ba0c2e", "img": "img/p/apple/ip12mini-product-red.jpg"}, {"name": "Blanc", "hex": "#f5f5f0", "img": "img/p/apple/ip12mini-blanc.jpg"}, {"name": "Noir", "hex": "#2b2b2d", "img": "img/p/apple/ip12mini-noir.jpg"}], options: ["64 Go", "128 Go"], desc: "Compact, écran OLED, 5G." },
  { id: "ip11pm", cat: "iphone", series: "iPhone 11", brand: "Apple", name: "iPhone 11 Pro Max", price: 200000, badge: "Reconditionné", colors: [{"name": "Vert nuit", "hex": "#4e5851", "img": "img/p/apple/ip11pm-vert-nuit.jpg"}, {"name": "Or", "hex": "#f5dcc4", "img": "img/p/apple/ip11pm-or.jpg"}, {"name": "Argent", "hex": "#e3e4e5", "img": "img/p/apple/ip11pm-argent.jpg"}, {"name": "Gris sidéral", "hex": "#4b4c4e", "img": "img/p/apple/ip11pm-gris-sideral.jpg"}], options: ["64 Go", "256 Go"], desc: "Triple caméra, grand écran OLED." },
  { id: "ip11p", cat: "iphone", series: "iPhone 11", brand: "Apple", name: "iPhone 11 Pro", price: 170000, badge: "Reconditionné", colors: [{"name": "Vert nuit", "hex": "#4e5851", "img": "img/p/apple/ip11p-vert-nuit.jpg"}, {"name": "Or", "hex": "#f5dcc4", "img": "img/p/apple/ip11p-or.jpg"}, {"name": "Argent", "hex": "#e3e4e5", "img": "img/p/apple/ip11p-argent.jpg"}, {"name": "Gris sidéral", "hex": "#4b4c4e", "img": "img/p/apple/ip11p-gris-sideral.jpg"}], options: ["64 Go", "256 Go"], desc: "Triple caméra, écran OLED." },
  { id: "ip11", cat: "iphone", series: "iPhone 11", brand: "Apple", name: "iPhone 11", price: 140000, badge: "Reconditionné", colors: [{"name": "Mauve", "hex": "#d1cde3", "img": "img/p/apple/ip11-mauve.jpg"}, {"name": "Vert", "hex": "#aee1cd", "img": "img/p/apple/ip11-vert.jpg"}, {"name": "Jaune", "hex": "#f7d14c", "img": "img/p/apple/ip11-jaune.jpg"}, {"name": "(PRODUCT)RED", "hex": "#ba0c2e", "img": "img/p/apple/ip11-product-red.jpg"}, {"name": "Blanc", "hex": "#f5f5f0", "img": "img/p/apple/ip11-blanc.jpg"}, {"name": "Noir", "hex": "#2b2b2d", "img": "img/p/apple/ip11-noir.jpg"}], options: ["64 Go", "128 Go"], desc: "Double caméra, très bonne autonomie." },
  { id: "ipxsmax", cat: "iphone", series: "iPhone X / XS / XR", brand: "Apple", name: "iPhone XS Max", price: 130000, badge: "Reconditionné", colors: [{"name": "Or", "hex": "#f5dcc4", "img": "img/p/apple/ipxsmax-or.jpg"}, {"name": "Argent", "hex": "#e3e4e5", "img": "img/p/apple/ipxsmax-argent.jpg"}, {"name": "Gris sidéral", "hex": "#4b4c4e", "img": "img/p/apple/ipxsmax-gris-sideral.jpg"}], options: ["64 Go", "256 Go"], desc: "Grand écran OLED 6,5 pouces, Face ID." },
  { id: "ipxs", cat: "iphone", series: "iPhone X / XS / XR", brand: "Apple", name: "iPhone XS", price: 110000, badge: "Reconditionné", colors: [{"name": "Or", "hex": "#f5dcc4", "img": "img/p/apple/ipxs-or.jpg"}, {"name": "Argent", "hex": "#e3e4e5", "img": "img/p/apple/ipxs-argent.jpg"}, {"name": "Gris sidéral", "hex": "#4b4c4e", "img": "img/p/apple/ipxs-gris-sideral.jpg"}], options: ["64 Go", "256 Go"], desc: "Écran OLED, Face ID, double caméra." },
  { id: "ipxr", cat: "iphone", series: "iPhone X / XS / XR", brand: "Apple", name: "iPhone XR", price: 110000, badge: "Reconditionné", colors: [{"name": "(PRODUCT)RED", "hex": "#ba0c2e", "img": "img/p/apple/ipxr-product-red.jpg"}, {"name": "Bleu", "hex": "#4bb7d8", "img": "img/p/apple/ipxr-bleu.jpg"}, {"name": "Jaune", "hex": "#f7d14c", "img": "img/p/apple/ipxr-jaune.jpg"}, {"name": "Corail", "hex": "#f2735a", "img": "img/p/apple/ipxr-corail.jpg"}, {"name": "Blanc", "hex": "#f5f5f0", "img": "img/p/apple/ipxr-blanc.jpg"}, {"name": "Noir", "hex": "#2b2b2d", "img": "img/p/apple/ipxr-noir.jpg"}], options: ["64 Go", "128 Go"], desc: "Écran 6,1 pouces, Face ID, six couleurs." },
  { id: "ipx", cat: "iphone", series: "iPhone X / XS / XR", brand: "Apple", name: "iPhone X", price: 90000, badge: "Reconditionné", colors: [{"name": "Argent", "hex": "#e3e4e5", "img": "img/p/apple/ipx-argent.jpg"}, {"name": "Gris sidéral", "hex": "#4b4c4e", "img": "img/p/apple/ipx-gris-sideral.jpg"}], options: ["64 Go", "256 Go"], desc: "Le premier iPhone sans bouton, Face ID." },
  { id: "ipse3", cat: "iphone", series: "iPhone SE", brand: "Apple", name: "iPhone SE (2022)", price: 120000, badge: "Reconditionné", colors: [{"name": "Minuit", "hex": "#232a31", "img": "img/p/apple/ipse3-minuit.jpg"}, {"name": "Lumière stellaire", "hex": "#f2ece4", "img": "img/p/apple/ipse3-lumiere-stellaire.jpg"}, {"name": "(PRODUCT)RED", "hex": "#ba0c2e", "img": "img/p/apple/ipse3-product-red.jpg"}], options: ["64 Go", "128 Go"], desc: "Puce A15, Touch ID, 5G, format compact." },
  { id: "ipse2", cat: "iphone", series: "iPhone SE", brand: "Apple", name: "iPhone SE (2020)", price: 80000, badge: "Reconditionné", colors: [{"name": "(PRODUCT)RED", "hex": "#ba0c2e", "img": "img/p/apple/ipse2-product-red.jpg"}, {"name": "Blanc", "hex": "#f5f5f0", "img": "img/p/apple/ipse2-blanc.jpg"}, {"name": "Noir", "hex": "#2b2b2d", "img": "img/p/apple/ipse2-noir.jpg"}], options: ["64 Go", "128 Go"], desc: "Touch ID, format compact, petit prix." },
  { id: "s26u", cat: "android", series: "Galaxy S", brand: "Samsung", name: "Galaxy S26 Ultra", price: 980000, badge: "Nouveau", colors: [{"name": "Bleu ciel", "hex": "#b3cbd9", "img": "img/p/samsung/s26u-bleu-ciel.jpg"}, {"name": "Noir", "hex": "#494d53", "img": "img/p/samsung/s26u-noir.jpg"}, {"name": "Cobalt Violet", "hex": "#686884", "img": "img/p/samsung/s26u-cobalt-violet.jpg"}, {"name": "Blanc", "hex": "#f3f4f5", "img": "img/p/samsung/s26u-blanc.jpg"}], options: ["256 Go", "512 Go", "1 To"], desc: "S Pen intégré, zoom 100x, Galaxy AI.", featured: true },
  { id: "s26p", cat: "android", series: "Galaxy S", brand: "Samsung", name: "Galaxy S26+", price: 780000, badge: "Nouveau", colors: [{"name": "Violet de cobalt", "hex": "#686884", "img": "img/p/samsung/s26p-violet-de-cobalt.jpg"}, {"name": "Noir", "hex": "#494d53", "img": "img/p/samsung/s26p-noir.jpg"}, {"name": "Bleu Ciel", "hex": "#b3cbd9", "img": "img/p/samsung/s26p-bleu-ciel.jpg"}, {"name": "Blanc", "hex": "#f3f4f5", "img": "img/p/samsung/s26p-blanc.jpg"}], options: ["256 Go", "512 Go"], desc: "Grand écran 6,7\", Galaxy AI, charge rapide 45 W." },
  { id: "s26", cat: "android", series: "Galaxy S", brand: "Samsung", name: "Galaxy S26", price: 650000, badge: "Nouveau", colors: [{"name": "Violet de cobalt", "hex": "#686884", "img": "img/p/samsung/s26-violet-de-cobalt.jpg"}, {"name": "Noir", "hex": "#494d53", "img": "img/p/samsung/s26-noir.jpg"}, {"name": "Bleu Ciel", "hex": "#b3cbd9", "img": "img/p/samsung/s26-bleu-ciel.jpg"}, {"name": "Blanc", "hex": "#f3f4f5", "img": "img/p/samsung/s26-blanc.jpg"}], options: ["256 Go"], desc: "Compact et puissant, Galaxy AI." },
  { id: "s26fe", cat: "android", series: "Galaxy S", brand: "Samsung", name: "Galaxy S26 FE", price: 420000, badge: "Neuf", colors: [{"name": "Pistache", "hex": "#bdcfce", "img": "img/p/samsung/s26fe-pistache.jpg"}, {"name": "Graphite", "hex": "#494d53", "img": "img/p/samsung/s26fe-graphite.jpg"}, {"name": "Myrtille", "hex": "#666e91", "img": "img/p/samsung/s26fe-myrtille.jpg"}], options: ["128 Go", "256 Go"], desc: "L'expérience Galaxy S à prix doux." },
  { id: "s25u", cat: "android", series: "Galaxy S", brand: "Samsung", name: "Galaxy S25 Ultra", price: 760000, oldPrice: 820000, badge: "Promo", colors: [{"name": "Bleu argenté titane", "hex": "#8e9fbc", "img": "img/p/samsung/s25u-bleu-argente-titane.jpg"}, {"name": "Noir titane", "hex": "#4a4a4d", "img": "img/p/samsung/s25u-noir-titane.jpg"}, {"name": "Gris titane", "hex": "#b3ab9e", "img": "img/p/samsung/s25u-gris-titane.jpg"}, {"name": "Blanc argenté titane", "hex": "#d9d9d6", "img": "img/p/samsung/s25u-blanc-argente-titane.jpg"}], options: ["256 Go", "512 Go", "1 To"], desc: "Titane, S Pen, appareil photo 200 Mpx." },
  { id: "s25fe", cat: "android", series: "Galaxy S", brand: "Samsung", name: "Galaxy S25 FE", price: 330000, badge: "Neuf", colors: [{"name": "Bleu glacé", "hex": "#becae9", "img": "img/p/samsung/s25fe-bleu-glace.jpg"}, {"name": "Marine", "hex": "#3c5b8a", "img": "img/p/samsung/s25fe-marine.jpg"}, {"name": "Noir de jais", "hex": "#494a4d", "img": "img/p/samsung/s25fe-noir-de-jais.jpg"}, {"name": "Blanc", "hex": "#f5f7f6", "img": "img/p/samsung/s25fe-blanc.jpg"}], options: ["128 Go", "256 Go"], desc: "Écran 120 Hz, triple caméra, Galaxy AI." },
  { id: "a57", cat: "android", series: "Galaxy A", brand: "Samsung", name: "Galaxy A57 5G", price: 260000, badge: "Nouveau", colors: [{"name": "Bleu Marine", "hex": "#383e4e", "img": "img/p/samsung/a57-bleu-marine.jpg"}, {"name": "Gris", "hex": "#7e7d80", "img": "img/p/samsung/a57-gris.jpg"}, {"name": "Lilas", "hex": "#a7b2e7", "img": "img/p/samsung/a57-lilas.jpg"}, {"name": "Bleu Glacé", "hex": "#c8d8eb", "img": "img/p/samsung/a57-bleu-glace.jpg"}], options: ["128 Go", "256 Go"], desc: "Super AMOLED 120 Hz, triple caméra 50 Mpx, 5G." },
  { id: "a37", cat: "android", series: "Galaxy A", brand: "Samsung", name: "Galaxy A37 5G", price: 200000, badge: "Nouveau", colors: [{"name": "Grisvert", "hex": "#5c707e", "img": "img/p/samsung/a37-grisvert.jpg"}, {"name": "Charbon", "hex": "#525257", "img": "img/p/samsung/a37-charbon.jpg"}, {"name": "Lavande", "hex": "#bcbde2", "img": "img/p/samsung/a37-lavande.jpg"}, {"name": "Blanc", "hex": "#f3f4f5", "img": "img/p/samsung/a37-blanc.jpg"}], options: ["128 Go", "256 Go"], desc: "Grand écran, charge rapide 45 W, 6 ans de mises à jour." },
  { id: "a27", cat: "android", series: "Galaxy A", brand: "Samsung", name: "Galaxy A27 5G", price: 165000, badge: "Neuf", colors: [{"name": "Vert clair", "hex": "#c5e9ea", "img": "img/p/samsung/a27-vert-clair.jpg"}, {"name": "Bleu", "hex": "#395081", "img": "img/p/samsung/a27-bleu.jpg"}, {"name": "Noir", "hex": "#3e4043", "img": "img/p/samsung/a27-noir.jpg"}], options: ["128 Go", "256 Go"], desc: "La 5G accessible avec un grand écran fluide." },
  { id: "a17", cat: "android", series: "Galaxy A", brand: "Samsung", name: "Galaxy A17 5G", price: 120000, badge: "Neuf", colors: [{"name": "Noir", "hex": "#404145", "img": "img/p/samsung/a17-noir.jpg"}, {"name": "Bleu", "hex": "#004680", "img": "img/p/samsung/a17-bleu.jpg"}, {"name": "Gris", "hex": "#9b9ca1", "img": "img/p/samsung/a17-gris.jpg"}], options: ["128 Go"], desc: "Grand écran, batterie 5000 mAh." },
  { id: "a07", cat: "android", series: "Galaxy A", brand: "Samsung", name: "Galaxy A07", price: 75000, badge: "Neuf", colors: [{"name": "Prune Clair", "hex": "#b6c0d6", "img": "img/p/samsung/a07-prune-clair.jpg"}, {"name": "Vert", "hex": "#304e53", "img": "img/p/samsung/a07-vert.jpg"}, {"name": "Noir", "hex": "#4a4f59", "img": "img/p/samsung/a07-noir.jpg"}], options: ["64 Go", "128 Go"], desc: "Le Galaxy essentiel à petit prix." },
  { id: "fold8u", cat: "android", series: "Galaxy Z Fold / Flip", brand: "Samsung", name: "Galaxy Z Fold8 Ultra", price: 1500000, badge: "Nouveau", colors: [{"name": "Ombre Violet", "hex": "#4f4f5c", "img": "img/p/samsung/fold8u-ombre-violet.jpg"}, {"name": "Graphite", "hex": "#5f6367", "img": "img/p/samsung/fold8u-graphite.jpg"}, {"name": "Crème", "hex": "#f1f1ee", "img": "img/p/samsung/fold8u-creme.jpg"}], options: ["256 Go", "512 Go", "1 To"], desc: "Le pliable ultime : grand écran, S Pen, zoom 200 Mpx.", featured: true },
  { id: "fold8", cat: "android", series: "Galaxy Z Fold / Flip", brand: "Samsung", name: "Galaxy Z Fold8", price: 1250000, badge: "Nouveau", colors: [{"name": "Lavande", "hex": "#bcb7ca", "img": "img/p/samsung/fold8-lavande.jpg"}, {"name": "Graphite", "hex": "#5f6367", "img": "img/p/samsung/fold8-graphite.jpg"}, {"name": "Crème", "hex": "#f1f1ee", "img": "img/p/samsung/fold8-creme.jpg"}], options: ["256 Go", "512 Go", "1 To"], desc: "Un smartphone qui s'ouvre en tablette." },
  { id: "flip8", cat: "android", series: "Galaxy Z Fold / Flip", brand: "Samsung", name: "Galaxy Z Flip8", price: 650000, badge: "Nouveau", colors: [{"name": "Rose", "hex": "#efc2e1", "img": "img/p/samsung/flip8-rose.jpg"}, {"name": "Graphite", "hex": "#5f6367", "img": "img/p/samsung/flip8-graphite.jpg"}, {"name": "Crème", "hex": "#f1f1ee", "img": "img/p/samsung/flip8-creme.jpg"}], options: ["256 Go", "512 Go"], desc: "Format clapet compact, grand écran externe." },
  { id: "fold7", cat: "android", series: "Galaxy Z Fold / Flip", brand: "Samsung", name: "Galaxy Z Fold7", price: 1000000, oldPrice: 1150000, badge: "Promo", colors: [{"name": "Bleu foncé", "hex": "#3c5b8a", "img": "img/p/samsung/fold7-bleu-fonce.jpg"}, {"name": "Noir nocturne", "hex": "#494a4d", "img": "img/p/samsung/fold7-noir-nocturne.jpg"}, {"name": "Ombre argentée", "hex": "#b0b7b9", "img": "img/p/samsung/fold7-ombre-argentee.jpg"}], options: ["256 Go", "512 Go", "1 To"], desc: "Le pliable le plus fin de sa génération." },
  { id: "flip7", cat: "android", series: "Galaxy Z Fold / Flip", brand: "Samsung", name: "Galaxy Z Flip7", price: 520000, badge: "Neuf", colors: [{"name": "Ombre bleue", "hex": "#3c5b8a", "img": "img/p/samsung/flip7-ombre-bleue.jpg"}, {"name": "Noir de jais", "hex": "#494a4d", "img": "img/p/samsung/flip7-noir-de-jais.jpg"}, {"name": "Rouge corail", "hex": "#ee6779", "img": "img/p/samsung/flip7-rouge-corail.jpg"}], options: ["256 Go", "512 Go"], desc: "Écran externe plein format, Galaxy AI." },
  { id: "xi17u", cat: "android", series: "Xiaomi / Redmi / POCO", brand: "Xiaomi", name: "Xiaomi 17 Ultra", price: 850000, badge: "Nouveau", img: "img/p/xiaomi/xi17u-photo.jpg", desc: "Photo Leica 1 pouce, quadruple caméra.", featured: true },
  { id: "xi17tp", cat: "android", series: "Xiaomi / Redmi / POCO", brand: "Xiaomi", name: "Xiaomi 17T Pro", price: 550000, badge: "Nouveau", img: "img/p/xiaomi/xi17tp-photo.jpg", desc: "Optique Leica, charge ultra-rapide." },
  { id: "xi17", cat: "android", series: "Xiaomi / Redmi / POCO", brand: "Xiaomi", name: "Xiaomi 17", price: 520000, badge: "Neuf", img: "img/p/xiaomi/xi17-photo.jpg", desc: "Compact, puissant, optique Leica." },
  { id: "rn15pp", cat: "android", series: "Xiaomi / Redmi / POCO", brand: "Xiaomi", name: "Redmi Note 15 Pro+ 5G", price: 300000, badge: "Neuf", img: "img/p/xiaomi/rn15pp-photo.jpg", desc: "Caméra 200 Mpx, charge 120 W, IP68." },
  { id: "rn15p", cat: "android", series: "Xiaomi / Redmi / POCO", brand: "Xiaomi", name: "Redmi Note 15 Pro", price: 230000, badge: "Neuf", img: "img/p/xiaomi/rn15p-photo.jpg", desc: "Écran AMOLED 120 Hz, caméra 200 Mpx." },
  { id: "rn15", cat: "android", series: "Xiaomi / Redmi / POCO", brand: "Xiaomi", name: "Redmi Note 15", price: 170000, badge: "Neuf", img: "img/p/xiaomi/rn15-photo.jpg", desc: "Grand écran AMOLED, grosse batterie." },
  { id: "ra7p", cat: "android", series: "Xiaomi / Redmi / POCO", brand: "Xiaomi", name: "Redmi A7 Pro", price: 70000, badge: "Neuf", img: "img/p/xiaomi/ra7p-photo.jpg", desc: "Le smartphone accessible au quotidien." },
  { id: "pocox8p", cat: "android", series: "Xiaomi / Redmi / POCO", brand: "POCO", name: "POCO X8 Pro", price: 260000, badge: "Neuf", img: "img/p/xiaomi/pocox8p-photo.jpg", desc: "Performances gaming, écran 120 Hz." },
  { id: "px10p", cat: "android", series: "Google Pixel", brand: "Google", name: "Pixel 10 Pro", price: 690000, badge: "Neuf", img: "img/p/autres/px10p-photo.jpg", desc: "Le meilleur de l'IA Google et un appareil photo d'exception." },
  { id: "mba13", cat: "ordinateur", series: "MacBook", brand: "Apple", name: "MacBook Air 13\"", price: 720000, badge: "Neuf", colors: [{"name": "Bleu ciel", "hex": "#c5d3e0", "img": "img/p/apple/mba13-bleu-ciel.jpg"}, {"name": "Argent", "hex": "#d9dadc", "img": "img/p/apple/mba13-argent.jpg"}, {"name": "Lumière stellaire", "hex": "#e8e1d4", "img": "img/p/apple/mba13-lumiere-stellaire.jpg"}, {"name": "Minuit", "hex": "#2e3640", "img": "img/p/apple/mba13-minuit.jpg"}], desc: "Ultra-fin, silencieux, jusqu'à 18 h d'autonomie.", featured: true },
  { id: "mba15", cat: "ordinateur", series: "MacBook", brand: "Apple", name: "MacBook Air 15\"", price: 890000, badge: "Neuf", colors: [{"name": "Minuit", "hex": "#2e3640", "img": "img/p/apple/mba15-minuit.jpg"}, {"name": "Bleu ciel", "hex": "#c5d3e0", "img": "img/p/apple/mba15-bleu-ciel.jpg"}, {"name": "Argent", "hex": "#d9dadc", "img": "img/p/apple/mba15-argent.jpg"}, {"name": "Lumière stellaire", "hex": "#e8e1d4", "img": "img/p/apple/mba15-lumiere-stellaire.jpg"}], desc: "Grand écran Liquid Retina dans un châssis léger." },
  { id: "mbp14", cat: "ordinateur", series: "MacBook", brand: "Apple", name: "MacBook Pro 14\"", price: 1450000, badge: "Neuf", colors: [{"name": "Noir sidéral", "hex": "#2e2f31", "img": "img/p/apple/mbp14-noir-sideral.jpg"}, {"name": "Argent", "hex": "#d9dadc", "img": "img/p/apple/mbp14-argent.jpg"}], desc: "Puissance pro, écran XDR, ports HDMI et SD." },
  { id: "hpomni", cat: "ordinateur", series: "PC Windows", brand: "HP", name: "HP OmniBook 17", price: 450000, badge: "Neuf", img: "img/p/autres/hpomni-photo.jpg", desc: "Grand écran 17,3\", idéal pour le bureau et les études." },
  { id: "dell14", cat: "ordinateur", series: "PC Windows", brand: "Dell", name: "Dell 14", price: 420000, badge: "Neuf", img: "img/p/autres/dell14-photo.jpg", desc: "Ordinateur 14\" léger et polyvalent." },
  { id: "thinkpad", cat: "ordinateur", series: "PC Windows", brand: "Lenovo", name: "ThinkPad X13", price: 650000, badge: "Neuf", img: "img/p/autres/thinkpad-photo.jpg", desc: "Le PC pro compact, robuste et léger." },
  { id: "vivobook", cat: "ordinateur", series: "PC Windows", brand: "ASUS", name: "ASUS Vivobook 14", price: 310000, badge: "Neuf", img: "img/p/autres/vivobook-photo.jpg", desc: "Écran Full HD, parfait pour le quotidien." },
  { id: "ipadair", cat: "tablette", series: "iPad", brand: "Apple", name: "iPad Air 11\"", price: 480000, badge: "Neuf", colors: [{"name": "Bleu", "hex": "#9bb6d1", "img": "img/p/apple/ipadair-bleu.jpg"}, {"name": "Violet", "hex": "#c7bde0", "img": "img/p/apple/ipadair-violet.jpg"}, {"name": "Gris sidéral", "hex": "#5e5f63", "img": "img/p/apple/ipadair-gris-sideral.jpg"}, {"name": "Lumière stellaire", "hex": "#ece6dc", "img": "img/p/apple/ipadair-lumiere-stellaire.jpg"}], desc: "Puce M, compatible Apple Pencil Pro." },
  { id: "ipad11", cat: "tablette", series: "iPad", brand: "Apple", name: "iPad 11\"", price: 290000, badge: "Neuf", colors: [{"name": "Bleu", "hex": "#a8c1dd", "img": "img/p/apple/ipad11-bleu.jpg"}, {"name": "Rose", "hex": "#f2c4cf", "img": "img/p/apple/ipad11-rose.jpg"}, {"name": "Jaune", "hex": "#f2dc85", "img": "img/p/apple/ipad11-jaune.jpg"}, {"name": "Argent", "hex": "#e3e4e6", "img": "img/p/apple/ipad11-argent.jpg"}], desc: "L'iPad idéal pour les études et les loisirs." },
  { id: "tabs11", cat: "tablette", series: "Galaxy Tab", brand: "Samsung", name: "Galaxy Tab S11", price: 560000, badge: "Nouveau", colors: [{"name": "Gris", "hex": "#75787b", "img": "img/p/samsung/tabs11-gris.jpg"}], options: ["128 Go"], desc: "Écran AMOLED, S Pen inclus." },
  { id: "tabs10fe", cat: "tablette", series: "Galaxy Tab", brand: "Samsung", name: "Galaxy Tab S10 FE", price: 340000, badge: "Neuf", colors: [{"name": "Bleu", "hex": "#aabdd4", "img": "img/p/samsung/tabs10fe-bleu.jpg"}, {"name": "Gris", "hex": "#75787b", "img": "img/p/samsung/tabs10fe-gris.jpg"}, {"name": "Argent", "hex": "#c7c8ca", "img": "img/p/samsung/tabs10fe-argent.jpg"}], options: ["128 Go", "256 Go"], desc: "Grand écran, S Pen inclus, IP68." },
  { id: "taba11", cat: "tablette", series: "Galaxy Tab", brand: "Samsung", name: "Galaxy Tab A11", price: 150000, badge: "Neuf", colors: [{"name": "Gris", "hex": "#75787b", "img": "img/p/samsung/taba11-gris.jpg"}, {"name": "Argent", "hex": "#c7c8ca", "img": "img/p/samsung/taba11-argent.jpg"}], options: ["64 Go", "128 Go"], desc: "La tablette familiale accessible." },
  { id: "aw12", cat: "montre", series: "Apple Watch", brand: "Apple", name: "Apple Watch Series 12", price: 360000, badge: "Nouveau", colors: [{"name": "Noir de jais", "hex": "#1f1f21", "img": "img/p/apple/aw12-noir-de-jais.jpg"}, {"name": "Gris sidéral", "hex": "#5b5d61", "img": "img/p/apple/aw12-gris-sideral.jpg"}, {"name": "Or clair", "hex": "#e9d9bd", "img": "img/p/apple/aw12-or-clair.jpg"}, {"name": "Bronze foncé", "hex": "#6b5547", "img": "img/p/apple/aw12-bronze-fonce.jpg"}], desc: "Suivi santé avancé, écran toujours activé.", featured: true },
  { id: "awultra", cat: "montre", series: "Apple Watch", brand: "Apple", name: "Apple Watch Ultra 4", price: 650000, badge: "Nouveau", colors: [{"name": "Titane naturel", "hex": "#b8b2a6", "img": "img/p/apple/awultra-titane-naturel.jpg"}, {"name": "Titane noir", "hex": "#2f3032", "img": "img/p/apple/awultra-titane-noir.jpg"}], desc: "Titane, GPS double fréquence, autonomie XXL." },
  { id: "awse", cat: "montre", series: "Apple Watch", brand: "Apple", name: "Apple Watch SE 3", price: 190000, badge: "Neuf", colors: [{"name": "Lumière stellaire", "hex": "#e9e2d6", "img": "img/p/apple/awse-lumiere-stellaire.jpg"}, {"name": "Minuit", "hex": "#2b2d31", "img": "img/p/apple/awse-minuit.jpg"}], desc: "L'essentiel de l'Apple Watch à petit prix." },
  { id: "gw9", cat: "montre", series: "Galaxy Watch", brand: "Samsung", name: "Galaxy Watch9", price: 220000, badge: "Nouveau", colors: [{"name": "Argent", "hex": "#9c9f9c", "img": "img/p/samsung/gw9-argent.jpg"}, {"name": "Graphite", "hex": "#404347", "img": "img/p/samsung/gw9-graphite.jpg"}], desc: "Suivi santé et sommeil, Galaxy AI." },
  { id: "gwu2", cat: "montre", series: "Galaxy Watch", brand: "Samsung", name: "Galaxy Watch Ultra 2", price: 420000, badge: "Nouveau", colors: [{"name": "Argent Titane", "hex": "#6d6e72", "img": "img/p/samsung/gwu2-argent-titane.jpg"}, {"name": "Gris titane", "hex": "#404347", "img": "img/p/samsung/gwu2-gris-titane.jpg"}], desc: "Titane, autonomie longue durée, pour l'aventure." },
  { id: "app3", cat: "audio", series: "AirPods", brand: "Apple", name: "AirPods Pro 3", price: 195000, badge: "Nouveau", colors: [{"name": "Blanc", "hex": "#f5f5f5", "img": "img/p/apple/app3-blanc.jpg"}], desc: "Réduction de bruit active, audio spatial, suivi cardiaque.", featured: true },
  { id: "ap4", cat: "audio", series: "AirPods", brand: "Apple", name: "AirPods 4 (réduction de bruit)", price: 120000, badge: "Neuf", colors: [{"name": "Blanc", "hex": "#f5f5f5", "img": "img/p/apple/ap4-blanc.jpg"}], desc: "Confort ouvert, réduction de bruit active, USB-C." },
  { id: "apmax", cat: "audio", series: "Casques", brand: "Apple", name: "AirPods Max", price: 390000, badge: "Neuf", colors: [{"name": "Minuit", "hex": "#2d2f33", "img": "img/p/apple/apmax-minuit.jpg"}, {"name": "Lumière stellaire", "hex": "#ece6dc", "img": "img/p/apple/apmax-lumiere-stellaire.jpg"}, {"name": "Bleu", "hex": "#8ea9c8", "img": "img/p/apple/apmax-bleu.jpg"}, {"name": "Violet", "hex": "#c9b7d6", "img": "img/p/apple/apmax-violet.jpg"}, {"name": "Orange", "hex": "#efa47a", "img": "img/p/apple/apmax-orange.jpg"}], desc: "Son haute fidélité, réduction de bruit active.", featured: true },
  { id: "beatsstudio", cat: "audio", series: "Casques", brand: "Beats", name: "Beats Studio Pro", price: 210000, badge: "Neuf", colors: [{"name": "Noir", "hex": "#1d1d1f", "img": "img/p/autres/beatsstudio-noir.jpg"}, {"name": "Bleu marine", "hex": "#2b3550", "img": "img/p/autres/beatsstudio-bleu-marine.jpg"}, {"name": "Sable", "hex": "#e6ddd0", "img": "img/p/autres/beatsstudio-sable.jpg"}], desc: "Son Beats signature, réduction de bruit, USB-C." },
  { id: "beatssolo4", cat: "audio", series: "Casques", brand: "Beats", name: "Beats Solo 4", price: 150000, badge: "Neuf", colors: [{"name": "Bleu ardoise", "hex": "#6d8fb3", "img": "img/p/autres/beatssolo4-bleu-ardoise.jpg"}], desc: "Léger, pliable, 50 h d'autonomie." },
  { id: "buds4p", cat: "audio", series: "Écouteurs", brand: "Samsung", name: "Galaxy Buds4 Pro", price: 165000, badge: "Nouveau", colors: [{"name": "Blanc", "hex": "#f3f4f5", "img": "img/p/samsung/buds4p-blanc.jpg"}, {"name": "Noir", "hex": "#494d53", "img": "img/p/samsung/buds4p-noir.jpg"}], desc: "Son Hi-Fi, réduction de bruit intelligente." },
  { id: "buds4", cat: "audio", series: "Écouteurs", brand: "Samsung", name: "Galaxy Buds4", price: 110000, badge: "Nouveau", colors: [{"name": "Blanc", "hex": "#f3f4f5", "img": "img/p/samsung/buds4-blanc.jpg"}, {"name": "Noir", "hex": "#494d53", "img": "img/p/samsung/buds4-noir.jpg"}], desc: "Écouteurs Galaxy confortables et précis." },
  { id: "buds3fe", cat: "audio", series: "Écouteurs", brand: "Samsung", name: "Galaxy Buds3 FE", price: 70000, badge: "Neuf", colors: [{"name": "Noir", "hex": "#4c525c", "img": "img/p/samsung/buds3fe-noir.jpg"}, {"name": "Gris", "hex": "#c8ccca", "img": "img/p/samsung/buds3fe-gris.jpg"}], desc: "Réduction de bruit à petit prix." },
  { id: "jbl", cat: "audio", series: "Enceintes", brand: "JBL", name: "Enceinte JBL Charge", price: 115000, badge: "Neuf", img: "img/p/jbl-charge.jpg", desc: "Son puissant, étanche, longue autonomie." },
  { id: "ps5", cat: "gaming", brand: "Sony", name: "PlayStation 5", price: 380000, badge: "Neuf", img: "img/p/autres/ps5-photo.jpg", desc: "Jeux en 4K, SSD ultra-rapide, manette DualSense incluse.", featured: true },
  { id: "ps5pro", cat: "gaming", brand: "Sony", name: "PlayStation 5 Pro", price: 560000, badge: "Neuf", img: "img/p/autres/ps5pro-photo.jpg", desc: "La PS5 la plus puissante, ray tracing avancé." },
  { id: "dualsense", cat: "gaming", brand: "Sony", name: "Manette DualSense", price: 55000, badge: "Neuf", img: "img/p/autres/dualsense-photo.jpg", desc: "Retour haptique et gâchettes adaptatives." },
  { id: "chg20", cat: "accessoires", brand: "Apple", name: "Chargeur USB-C 20 W", price: 15000, badge: "Original", img: "img/p/autres/chg20-photo.jpg", desc: "Charge rapide pour iPhone et iPad." },
  { id: "magsafe", cat: "accessoires", brand: "Apple", name: "Chargeur MagSafe", price: 35000, badge: "Original", img: "img/p/autres/magsafe-photo.jpg", desc: "Charge sans fil magnétique rapide." },
  { id: "cable", cat: "accessoires", brand: "Apple", name: "Câble USB-C tissé", price: 10000, badge: "Original", img: "img/p/autres/cable-photo.jpg", desc: "Câble de charge et de synchronisation." },
  { id: "coque", cat: "accessoires", brand: "Hi-Tech", name: "Coque + verre trempé", price: 7500, badge: "Pack", options: ["iPhone", "Samsung", "Autre modèle"], desc: "Protection complète, pose du verre offerte en boutique." },
  { id: "pb", cat: "accessoires", brand: "Anker", name: "Batterie externe 20 000 mAh", price: 25000, badge: "Neuf", desc: "Charge rapide PD, recharge un iPhone plus de 4 fois." }
];
